[tool.poetry]
name = "toc-editor"
readme = "README.md"
packages = [{ include = "toc_editor", from = "src" }]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pdf-tocgen = "^1.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
